skip-check:
  - CKV_AWS_290
  - CKV_AWS_355
  - CKV_AWS_68
  - CKV_AWS_310
  - CKV_AWS_374
  - CKV2_AWS_32
  - CKV2_AWS_47
  - CKV2_AWS_38
  - CKV2_AWS_39
  - CKV2_AWS_62
  - CKV2_AWS_61
  - CKV_AWS_144
  - CKV_AWS_145
  - CKV_AWS_21
  - CKV2_AWS_65
